<!DOCTYPE HTML>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
        <!-- CSS JQ -->
        <link rel="stylesheet" href="./styles/jquery/jquery-ui-1.8.16.tel_mob.css" type="text/css">
        <link rel="stylesheet" href="./styles/jquery/jquery.mobile-1.0.css" type="text/css">
        <link rel="stylesheet" href="./styles/jquery/jquery.mobile.simpledialog.min.css" type="text/css">
        <link rel="stylesheet" href="./styles/jquery/jquery.mobile.datebox.min.css" type="text/css">
                
        <!-- JS JQ -->
        <script type="text/javascript" src="./js/jquery/jquery-1.7.1.min.js"></script>
        <script type="text/javascript" src="./js/custom/js_mtbkey_jqmobile_config.js"></script>
        <!-- login.js-->
        <!--<script type="text/javascript" src="./js/jquery-ui-1.8.16.tel_mob.min.js"></script> quitado-->
        <script type="text/javascript" src="./js/jquery/jquery.mobile-1.0.1.min.js"></script>
        <script type="text/javascript" src="./js/jquery/jquery.mobile.simpledialog.js"></script>
        <script type="text/javascript" src="./js/jquery/jquery.mobile.datebox.js"></script>
       
        <!-- JS MTB -->
        <script type="text/javascript" src="./js/custom/js_mtbkey_datebox_config.js"></script>
        <script type="text/javascript" src="./js/custom/js_mtbkey_control.js"></script>
        <script type="text/javascript" src="./js/custom/js_mtbkey_ajax.js"></script>
        <script type="text/javascript" src="./js/custom/js_mtbkey_dni_checker.js"></script>
        <script type="text/javascript" src="./js/custom/js_mtbkey_discount_links.js"></script>
        <script type="text/javascript" src="./js/custom/js_mtbkey_multiselect.js"></script>
        
        <!-- CSS MTB -->
        <link rel="stylesheet" href="./styles/custom/css_mtbkey_jqmobile.css" type="text/css">
        <link rel="stylesheet" href="./styles/custom/css_mtbkey_custom.css" type="text/css">
        <link rel="stylesheet" href="./styles/custom/css_debug.css" type="text/css">
        <title><?php echo $oSite->get_page_title(); ?></title>
    </head>
    <body>
        <!--page-->	
        <div id="divPage" data-role="page" style="">   